<a href="https://colab.research.google.com/github/faisalnawazmir/Econometrics-ML_for_Finance/blob/main/ayesha__Fama_q5_Factor_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fama French Q5 Factor Model  using split data
2000-2005,2006-2008,2009-2012,2013-2016,2017-2019 (5 splits)

In [87]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm 
from tabulate import tabulate
import time
np.random.seed(12345)

In [250]:
#copying data from excel file 25 portfoli
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive
file = r'/gdrive/My Drive/data/q_q5_data_sheet.xlsx'
df = pd.read_excel(file, sheet_name='2017-2019')
df.head()
sb='2017-2019'

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [251]:
# dropping passed columns
df.drop(["Unnamed: 6","Unnamed: 7", "Unnamed: 8","Date.1"], axis = 1, inplace = True)
df.head()
#You must specify the axis argument. default is axis = 0 which is rows columns is axis = 1.

Date       MKt        Me  ...       p23       p24       p25
0 2017-01-01  0.014843 -0.011870  ... -0.009265 -0.003336 -0.005026
1 2017-01-02 -0.009441  0.027685  ... -0.016385 -0.003015 -0.011921
2 2017-01-03 -0.012673  0.006536  ...  0.015195  0.011838  0.000796
3 2017-01-04  0.018650 -0.018119  ... -0.041960 -0.047804 -0.060721
4 2017-01-05  0.020995  0.030408  ...  0.006389 -0.001668 -0.004995

[5 rows x 31 columns]

In [253]:
#N = 25  # of firms in an economy, here # of portfolios, here len(data)
T = len(df)  # length of periods # here 1136#df.columns.array
#  data
data = df.loc[:,'p1':'p25']
#data.shape#(T,N)
#x,y=data.shape
#N=y#  # of firms in an economy, here # of portfolios, here len(data)
#T = data.shape[0]
N = data.shape[1]

In [254]:
# simulate factor loadings (ie, coefficients)
b_mkt = np.zeros((1,N)) # true loadings for market factor
b_me = np.zeros((1,N)) # true loadings for size factor
b_roe = np.zeros((1,N)) # true loadings for value factor
b_ia = np.zeros((1,N)) # true loadings for value factor
b_reg = np.zeros((1,N)) # true loadings for value factor

In [255]:
#  factor returns
mkt = df['MKt'] # market factor
me = df['Me'] # size factor
roe = df['ROE'] # value factor
ia = df['I/A'] # market factor
reg=df['Reg']# umd is growth factor


In [256]:
#data.iloc[:,1]
fctrs = df[["MKt","Me","ROE","I/A","Reg"]]
fctrs.head()


MKt        Me       ROE       I/A       Reg
0  0.014843 -0.011870 -0.039684 -0.064430 -0.043967
1 -0.009441  0.027685  0.053202  0.024197  0.033439
2 -0.012673  0.006536  0.040037  0.031361  0.052201
3  0.018650 -0.018119  0.011972 -0.023361 -0.019770
4  0.020995  0.030408  0.037446  0.026583  0.074397

In [257]:
no_factors=fctrs.shape[1]

In [258]:
# Step 1: time series regression firm by firm
#fctrs = np.c_[mkt, smb, hml]
# of factors
b = np.zeros(no_factors)
for i in range(N): # firm-by-firm time series regression
  model = LinearRegression()
  model.fit(fctrs,data.iloc[:,i])
  b = np.c_[b,model.coef_]

b  = np.transpose(b[:,1:])
b.shape
#b should be 0.1, 0.2

(25, 5)

In [278]:
#b is bhat
#b
#b.shape# (N,#factors)
df_bhat = pd.DataFrame(b)
df_bhat.columns = ['b_01','b_02','b_03','b_04','b_05']# change according factos
#print(df_bhat.head())

from google.colab import  drive
df_bhat.to_csv('/gdrive/My Drive/data/bhat_ayesha_q5_factors_split_'+sb+'.csv')

In [260]:
# Step 2: cross sectional regression time-by-time
f = np.zeros(no_factors)
for i in range(T): # time-by-time cross sectional regression
  model = LinearRegression()
  model.fit(b,data.iloc[i,:])
  f = np.c_[f,model.coef_]

f = np.transpose(f[:,1:])
df_gamma = pd.DataFrame(f)
df_gamma.columns = ['mkt','me','roe','ia','reg']
print(df_gamma.describe())
print('Median estimate:', np.median(f,axis=0))
print('Standard errors (without Shanken correction):', np.std(f,axis=0)/T**.5)

             mkt         me        roe         ia        reg
count  36.000000  36.000000  36.000000  36.000000  36.000000
mean   -0.002926   0.002168   0.006053  -0.006796  -0.001178
std     0.062072   0.028074   0.068374   0.060681   0.056111
min    -0.138497  -0.051924  -0.165808  -0.183760  -0.107212
25%    -0.036568  -0.019526  -0.051942  -0.030593  -0.050428
50%    -0.009774  -0.001033   0.012401  -0.003815   0.010747
75%     0.031368   0.016206   0.051696   0.017209   0.030869
max     0.195525   0.064088   0.186587   0.128577   0.145424
Median estimate: [-0.00977425 -0.0010325   0.01240052 -0.00381473  0.01074719]
Standard errors (without Shanken correction): [0.0102006  0.0046136  0.01123631 0.00997204 0.00922105]


## Writing output to the text file

In [261]:
file_output=r'/gdrive/My Drive/data/output_q5factor_split_'+sb+'.txt'
desc=repr(df_gamma.describe())
median_est=repr(np.median(f,axis=0))
std_err=repr(np.std(f,axis=0)/T**.5)

Using the with statement is better practice, it automatically closes the file even if the code encounters an exception. The code will run everything in the indent block then close the file object. 

In [262]:
# Write lines to file

with open(file_output, 'w+') as writefile:
    writefile.write("Results of Table  A\n")
    writefile.write(desc+"\n")
    writefile.write("Median estimate:"+"\t"+median_est+"\n")
    writefile.write("Standard errors (without Shanken correction):\t"+std_err+"\n")
    writefile.write("T stats: \t"+t_stat_boot+"\n")
    writefile.write("***********\n\n")


In [263]:
# Check whether write to file

with open(file_output, 'r') as testwritefile:
    print(testwritefile.read())

Results of Table  A
             mkt         me        roe         ia        reg
count  36.000000  36.000000  36.000000  36.000000  36.000000
mean   -0.002926   0.002168   0.006053  -0.006796  -0.001178
std     0.062072   0.028074   0.068374   0.060681   0.056111
min    -0.138497  -0.051924  -0.165808  -0.183760  -0.107212
25%    -0.036568  -0.019526  -0.051942  -0.030593  -0.050428
50%    -0.009774  -0.001033   0.012401  -0.003815   0.010747
75%     0.031368   0.016206   0.051696   0.017209   0.030869
max     0.195525   0.064088   0.186587   0.128577   0.145424
Median estimate:	array([-0.00977425, -0.0010325 ,  0.01240052, -0.00381473,  0.01074719])
Standard errors (without Shanken correction):	array([0.0102006 , 0.0046136 , 0.01123631, 0.00997204, 0.00922105])
T stats: 	array([-0.33404899,  0.15290147,  0.08303993, -0.33042091, -0.13865824])
***********




In [264]:
mu=np.median(f,axis=0)
sigma=(np.std(f,axis=0))/T**.5
tstat=mu/sigma
tstat
#tstat<1.96

array([-0.95820271, -0.22379491,  1.10361128, -0.38254266,  1.16550625])

In [265]:
f.shape # (T,#factors)# f or df I assume is gamma hat
df_gamma.to_csv('/gdrive/My Drive/data/ayesha_gamma_q5_factors_split_'+sb+'.csv')

In [232]:
#df.head()#f and df are same, gamma hat

In [266]:
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np
import statsmodels.stats.api as sms

In [267]:
data_a=data.to_numpy()
fctrs_a=fctrs.to_numpy()

In [268]:
# Compute standard error with bootstrapping (Shanken correction unnecessary)
# One simple bootstrapping 

indices = np.random.randint(low=0,high=T, size=T)
new_data = data_a[indices,:]
new_fctrs = fctrs_a[indices,:]
xx = indices[0]
print(xx)
print(new_data[0,:])
print(data_a[xx,:])


0
[ 0.02810089  0.03543928  0.02906048  0.03717424  0.01791768  0.01885901
  0.00481384  0.00915086  0.01590029  0.01750385  0.00439697  0.00588828
 -0.00214039 -0.00879516 -0.01101614  0.00844586  0.01177861  0.01097148
  0.00939897  0.00428022 -0.00307801 -0.00120318 -0.00926488 -0.00333638
 -0.00502559]
[ 0.02810089  0.03543928  0.02906048  0.03717424  0.01791768  0.01885901
  0.00481384  0.00915086  0.01590029  0.01750385  0.00439697  0.00588828
 -0.00214039 -0.00879516 -0.01101614  0.00844586  0.01177861  0.01097148
  0.00939897  0.00428022 -0.00307801 -0.00120318 -0.00926488 -0.00333638
 -0.00502559]


In [269]:
def efhats(data,fctrs): # function to compute average estimated factor return
  T = data.shape[0]
  N = data.shape[1]
  # Step 1: Time series regression
  x = np.c_[np.ones(T),fctrs]
  M = np.linalg.inv(x.T @ x) @ x.T
  bhat = (M @ data)[1:,:].T

  # Step 2: cross sectional regression
  # Include other control variables here (eg, firm characteristics)
  x = np.c_[np.ones(N),bhat]
  M = np.linalg.inv(x.T @ x) @ x.T
  fhat = (M @ data.T)[1:,:].T
  df = pd.DataFrame(fhat)
  df.columns = ['mkt','me','roe','ia','reg']
  E_fhat = np.average(fhat,axis=0)
  return E_fhat 


In [270]:
E_fhat = efhats(data_a,fctrs_a)
simn = 10**3 # of bootstrapping
t = time.time() # bootstrapping start time 
for i in range(simn): 
  indices = np.random.randint(low=0,high=T,size=T) # resample by rows
  new_data = data_a[indices,:] # resampled stock return data
  new_fctrs = fctrs_a[indices,:] # resampled factor return data
  E_fhat = np.c_[E_fhat,efhats(new_data,new_fctrs)]
  # to check bootstrapping status
  if i % 100 == 0: print(i)

print('Simulation duration:', time.time()-t, 'seconds.')
df = pd.DataFrame(E_fhat.T)
df.columns = ['mkt','me','roe','ia','reg']
print(df.describe())

0
100
200
300
400
500
600
700
800
900
Simulation duration: 0.9875690937042236 seconds.
               mkt           me          roe           ia          reg
count  1001.000000  1001.000000  1001.000000  1001.000000  1001.000000
mean     -0.003043     0.000679     0.001443    -0.004427    -0.001863
std       0.010736     0.004550     0.010859     0.011342     0.010344
min      -0.043712    -0.019117    -0.031876    -0.046226    -0.049394
25%      -0.009870    -0.002042    -0.006002    -0.011761    -0.008748
50%      -0.002925     0.000599     0.001508    -0.004892    -0.001871
75%       0.004220     0.003475     0.008818     0.002932     0.004660
max       0.036575     0.014895     0.039805     0.040596     0.029525


In [271]:
print('FM regression esimate of expeced factor returns: \n', np.average(E_fhat.T,axis=0))
print('FM regression esimate of standard errors: \n', np.std(E_fhat.T,axis=0))

FM regression esimate of expeced factor returns: 
 [-0.00304286  0.00067949  0.00144319 -0.0044274  -0.00186311]
FM regression esimate of standard errors: 
 [0.01073087 0.0045474  0.01085313 0.01133675 0.0103384 ]


In [272]:
#bootstrap t stats
mu_boot=np.average(E_fhat.T,axis=0)
sigma_boot=np.std(E_fhat.T,axis=0)
tstat_boot=mu_boot/sigma_boot
tstat_boot

array([-0.28356152,  0.14942421,  0.13297409, -0.3905351 , -0.18021228])

https://quant.stackexchange.com/questions/35781/how-to-interpret-the-grs-f-test-values
#grs test
https://stackoverflow.com/questions/24074481/fama-macbeth-regression-in-python-pandas-or-statsmodels

In [ ]:
pip install rpy2

In [41]:
%load_ext rpy2.ipython

In [42]:
%%R -i df -w 5 -h 5 --units in -r 200
# import df from global environment
# make default figure size 5 by 5 inches with 200 dpi resolution

install.packages("GRS.test", repos='http://cran.us.r-project.org', quiet=TRUE)
library(GRS.test)


In [273]:
%%R -i data,fctrs
GRS.MLtest(data, fctrs)

$GRS.stat
          GRS
[1,] 2.045462

$GRS.pval
           GRS
[1,] 0.1896439

$thetas
         [,1]
[1,] 2.946525

$theta
          [,1]
[1,] 0.4415546

$ratio
          [,1]
[1,] 0.1498561



In [241]:
%%R -o model -o coef  -o pval -o thetas -o theta -o ratio
model<-GRS.MLtest(data, fctrs)
coef<-model$GRS.stat
pval<-model$GRS.pval
thetas<-model$thetas
theta<-model$theta
ratio<-model$ratio

In [242]:
print(model)

$GRS.stat
          GRS
[1,] 2.045462

$GRS.pval
           GRS
[1,] 0.1896439

$thetas
         [,1]
[1,] 2.946525

$theta
          [,1]
[1,] 0.4415546

$ratio
          [,1]
[1,] 0.1498561




W statistic given in (7) of GRS (1989) <DOI:10.2307/1913625>

GRS.stat=GRS test statistic

GRS.pval=its p-value

theta=maximum Sharpe ratio of the K factor portfolios

thetas=slope of the efficient frontier based on all assets

ratio=theta/thetas, proportion of the potential efficiency

References
Gibbons, Ross, Shanken, 1989. A test of the efficiency of a given portfolio, Econometrica, 57,1121-
1152. <DOI:10.2307/1913625>


https://towardsdatascience.com/guide-to-r-and-python-in-a-single-jupyter-notebook-ff12532eb3ba

https://www.linkedin.com/pulse/interfacing-r-from-python-3-jupyter-notebook-jared-stufft/
how to switch R and python


In [274]:
grs_stat=repr(coef)
grs_pval=repr(pval)
grs_thets=repr(thetas)
grs_theta=repr(theta)
grs_ratio=repr(ratio)

In [275]:
#bootstrap t stat results
simulated_desc=repr(df.describe())
median_est_boot=repr(mu_boot)
std_err_boot=repr(sigma_boot)
t_stat_boot=repr(tstat_boot)

In [276]:
# Write lines to file

with open(file_output, 'a') as writefile:
    writefile.write("\n Results of Boot Strapping Table  B\n")
    writefile.write(simulated_desc+"\n")
    writefile.write("FM regression esimate of expeced factor returns:"+"\t"+median_est_boot+"\n")
    writefile.write("FM regression esimate of standard errors:\t"+std_err_boot+"\n")
    writefile.write("Tstats boot strapping: \t"+t_stat_boot+"\n")
    writefile.write("**********\n")
    writefile.write("\t GRS Test:\n")
    writefile.write("**********\n")
    writefile.write("GRS stat:\t"+grs_stat+"\n")
    writefile.write("GRS pvalue:\t"+grs_pval+"\n")
    writefile.write("GRS thetas:\t"+grs_thets+"\n")
    writefile.write("GRS theta:\t"+grs_theta+"\n")
    writefile.write("GRS ratio:\t"+grs_ratio+"\n")

In [84]:
# Erasing the file contents of a text file will result in an empty text file.
# file = open(file_output,"r+")
# file.truncate(0)
# file.close()